spring:
  datasource:
    url: jdbc:mysql://localhost:3306/info_hub?createDatabaseIfNotExist=true
    username: root
    password: 0915404712
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    exp-reset-token: 5 # forgot password
    username: hoangnam11pdp@gmail.com
    password: iabcuwfkilwjzwgp #STMP
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
jwt:
  # seconds
  exp-access-token: 86400 #86400 # 1 day
  exp-refresh-token: 604800 # seconds
  secretKey: 9e8896ae0f4b75d6633c835079b60a73ed0102977da741d3ebe357745fcc6a1c
api:
  prefix: api/v1
#  url-mail: http://localhost:8080/api/auth/reset-password?token=
  url-mail: http://192.168.17.118:3000/resetpassword?token=

